apiVersion: v1
kind: Namespace
metadata:
  name: techblog-draft
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jekyll-website
  namespace: techblog-draft
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jekyll-website
  template:
    metadata:
      labels:
        app: jekyll-website  
    spec:
      containers:
      - name: website
        image: registry.11stcorp.com/it-team/techblog-draft:1.0.0
        ports:
          - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: jekyll-website
  namespace: techblog-draft
spec:
  type: ClusterIP
  selector:
    app: jekyll-website
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: techblog-draft-ingress
  namespace: techblog-draft
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
  - hosts:
    - 11stcorp.com
    secretName: 11stcorp-tls-cert
  rules:
  - host: techblog-draft.11stcorp.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jekyll-website
            port:
              number: 80
